remote sync

diff --git a/bin/remote_mirror_sync b/bin/remote_mirror_sync
--- a/bin/remote_mirror_sync
+++ b/bin/remote_mirror_sync
@@ -1,43 +1,45 @@
 #!/usr/bin/env bash
 
-while getopts m:o:v args
+while getopts l:m:o:v args
 do
     case "${args}" in
+        l) location=${OPTARG};;
         m) mjd=${OPTARG};;
         o) obs=${OPTARG};;
         v) verbose=true;;
     esac
 done
 
-
-if [ -z "${mjd}" ]; then
-    NOW=$(date +"%Y%m%d")
-    mjd=$(( ( $(date +%s -d "$NOW") / 86400 ) + 40587 ))
-fi
-
-re='^[0-9]{5}$'
-if [[ $mjd =~ $re ]]; then
-    if [[ "$obs" = "apo" ]]; then
-        sections="spectro ecam fcam gcam sos apogee quickred"
-    elif [[ "$obs" = "lco" ]]; then
-        sections="apogee fcam gcam spectro sos quickred"
-    elif [[ "$obs" = "lvm" ]]; then
-        sections="lvm_spectro lvm_agcam "
-    else
-        echo "REMOTE_MIRROR_SYNC> invalid observatory: $obs"
-        exit 6
-    fi
-else
-    echo "REMOTE_MIRROR_SYNC> invalid mjd: $mjd"
-    exit 6
-fi
-
 if [ -z "${TRANSFER_SYNC_USER}" ] || [ -z "${TRANSFER_SYNC_HOST}" ]; then
     echo "Error: TRANSFER_SYNC_USER and TRANSFER_SYNC_HOST environment variables must be set."
     exit 1
 fi
 
-command="transfer_mirror_sync -o $obs -m $mjd -S $sections"
+if [ -n "${location}" ]; then
+    command="transfer_mirror_sync -l $location"
+else
+    if [ -z "${mjd}" ]; then
+        NOW=$(date +"%Y%m%d")
+        mjd=$(( ( $(date +%s -d "$NOW") / 86400 ) + 40587 ))
+    fi
+    re='^[0-9]{5}$'
+    if [[ $mjd =~ $re ]]; then
+        if [[ "$obs" = "apo" ]]; then
+            sections="spectro ecam fcam gcam sos apogee quickred"
+        elif [[ "$obs" = "lco" ]]; then
+            sections="apogee fcam gcam spectro sos quickred"
+        elif [[ "$obs" = "lvm" ]]; then
+            sections="lvm_spectro lvm_agcam "
+        else
+            echo "REMOTE_MIRROR_SYNC> invalid observatory: $obs"
+            exit 6
+        fi
+    else
+        echo "REMOTE_MIRROR_SYNC> invalid mjd: $mjd"
+        exit 6
+    fi
+fi
+
 if [ "$verbose" = true ]; then
     command="$command -v"
     echo "REMOTE> $command"
