remote sync

diff --git a/bin/remote_mirror_sync b/bin/remote_mirror_sync
--- a/bin/remote_mirror_sync
+++ b/bin/remote_mirror_sync
@@ -32,8 +32,15 @@ else
     exit 6
 fi
 
-command="transfer_mirror_sync -o $obj -m $mjd -S $sections"
+if [ -z "${TRANSFER_SYNC_USER}" ] || [ -z "${TRANSFER_SYNC_HOST}" ]; then
+    echo "Error: TRANSFER_SYNC_USER and TRANSFER_SYNC_HOST environment variables must be set."
+    exit 1
+fi
+
+command="transfer_mirror_sync -o $obs -m $mjd -S $sections"
 if [ "$verbose" = true ]; then
     command="$command -v"
     echo "REMOTE> $command"
 fi
+
+ssh "${TRANSFER_SYNC_USER}@${TRANSFER_SYNC_HOST}" "${command}"
